### ISSUE TITLE
New accounts does not show in Receive

### ISSUE THREAD

**Issue by joomlaproffs** [andrepatta/etn-desktop-wallet#5]
I think this might be a bug here. 

If I go to "Account" and create new Account these will not show up under "Receive". It will only show "Primary Account", however this is not the Primary Account but the latest account that I have created. If I copy this Primary address I notice its the latest Public Address created in the "Account" area and no other accounts is listed here. 

I am on Windows 10 here.

**Comment by andrepatta** [comment]
Hi @joomlaproffs ,

What you see in the "Receive" tab are the sub-addresses for the selected account. Notice that it says "Primary Address", not "Primary Account" in the "Receive" tab.

Thanks

**Comment by joomlaproffs** [comment]
Ah! That explains it! Thank you!

**Comment by andrepatta** [comment]
No problem!
